# Generated by Django 4.2.2 on 2023-06-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='reference_name',
            field=models.CharField(default='none', max_length=120),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Part-time', 'parttime'), ('Full-time', 'fulltime'), ('Freelancer', 'freelancer')], max_length=20),
        ),
    ]
