# Generated by Django 4.2.2 on 2023-06-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_reference_name_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
