# Generated by Django 4.2.2 on 2023-07-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='connect',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
