# Generated by Django 4.2.2 on 2023-09-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
